/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlgorithmItem: typeof import('./src/components/AlgorithmItem.vue')['default']
    CustomDialog: typeof import('./src/components/CustomDialog.vue')['default']
    DefaultButton: typeof import('./src/components/DefaultButton.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    InfoTooltip: typeof import('./src/components/InfoTooltip.vue')['default']
    MemberCard: typeof import('./src/components/MemberCard.vue')['default']
    MembershipItem: typeof import('./src/components/MembershipItem.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadowButton: typeof import('./src/components/ShadowButton.vue')['default']
    ToggleButton: typeof import('./src/components/ToggleButton.vue')['default']
  }
}
