/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AlgorithmStorePage': RouteRecordInfo<'/AlgorithmStorePage', '/AlgorithmStorePage', Record<never, never>, Record<never, never>>,
    '/BasicDesignerPage': RouteRecordInfo<'/BasicDesignerPage', '/BasicDesignerPage', Record<never, never>, Record<never, never>>,
    '/BasicDirectedEvolutionResultsPage': RouteRecordInfo<'/BasicDirectedEvolutionResultsPage', '/BasicDirectedEvolutionResultsPage', Record<never, never>, Record<never, never>>,
    '/BasicGlobalCADScorePage': RouteRecordInfo<'/BasicGlobalCADScorePage', '/BasicGlobalCADScorePage', Record<never, never>, Record<never, never>>,
    '/BasicLocalCADScorePage': RouteRecordInfo<'/BasicLocalCADScorePage', '/BasicLocalCADScorePage', Record<never, never>, Record<never, never>>,
    '/BasicMatchingResultsPage': RouteRecordInfo<'/BasicMatchingResultsPage', '/BasicMatchingResultsPage', Record<never, never>, Record<never, never>>,
    '/BasicResultDetailsPage': RouteRecordInfo<'/BasicResultDetailsPage', '/BasicResultDetailsPage', Record<never, never>, Record<never, never>>,
    '/BasicStabilityEvaluationPage': RouteRecordInfo<'/BasicStabilityEvaluationPage', '/BasicStabilityEvaluationPage', Record<never, never>, Record<never, never>>,
    '/BasicVariantDetailsPage': RouteRecordInfo<'/BasicVariantDetailsPage', '/BasicVariantDetailsPage', Record<never, never>, Record<never, never>>,
    '/ContactFormPage': RouteRecordInfo<'/ContactFormPage', '/ContactFormPage', Record<never, never>, Record<never, never>>,
    '/ContactUsPage': RouteRecordInfo<'/ContactUsPage', '/ContactUsPage', Record<never, never>, Record<never, never>>,
    '/DynamicDesignerPage': RouteRecordInfo<'/DynamicDesignerPage', '/DynamicDesignerPage', Record<never, never>, Record<never, never>>,
    '/FAQsPage': RouteRecordInfo<'/FAQsPage', '/FAQsPage', Record<never, never>, Record<never, never>>,
    '/FeedbackPage': RouteRecordInfo<'/FeedbackPage', '/FeedbackPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/MembershipPlanPage': RouteRecordInfo<'/MembershipPlanPage', '/MembershipPlanPage', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/NotFoundPage', Record<never, never>, Record<never, never>>,
    '/TeamPage': RouteRecordInfo<'/TeamPage', '/TeamPage', Record<never, never>, Record<never, never>>,
    '/TechnicalResourcesPage': RouteRecordInfo<'/TechnicalResourcesPage', '/TechnicalResourcesPage', Record<never, never>, Record<never, never>>,
    '/UserGuidePage': RouteRecordInfo<'/UserGuidePage', '/UserGuidePage', Record<never, never>, Record<never, never>>,
    '/VideoTutorialsPage': RouteRecordInfo<'/VideoTutorialsPage', '/VideoTutorialsPage', Record<never, never>, Record<never, never>>,
    '/WikiPage': RouteRecordInfo<'/WikiPage', '/WikiPage', Record<never, never>, Record<never, never>>,
  }
}
