/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/ContactUsPage': RouteRecordInfo<'/ContactUsPage', '/ContactUsPage', Record<never, never>, Record<never, never>>,
    '/DynamicDesignerPage': RouteRecordInfo<'/DynamicDesignerPage', '/DynamicDesignerPage', Record<never, never>, Record<never, never>>,
    '/FeedbackPage': RouteRecordInfo<'/FeedbackPage', '/FeedbackPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/IntroductionPage': RouteRecordInfo<'/IntroductionPage', '/IntroductionPage', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/NotFoundPage', Record<never, never>, Record<never, never>>,
    '/TeamPage': RouteRecordInfo<'/TeamPage', '/TeamPage', Record<never, never>, Record<never, never>>,
    '/TechnicalResourcesPage': RouteRecordInfo<'/TechnicalResourcesPage', '/TechnicalResourcesPage', Record<never, never>, Record<never, never>>,
    '/UserGuidePage': RouteRecordInfo<'/UserGuidePage', '/UserGuidePage', Record<never, never>, Record<never, never>>,
    '/WikiPage': RouteRecordInfo<'/WikiPage', '/WikiPage', Record<never, never>, Record<never, never>>,
  }
}
