import {ref} from 'vue'

interface PredictionResult {
  fpId: string
  signalId: string
  linkerId: string
  fusionProtein: string
  stabilityScore: number
  linker: string
  signal: string
}

export const apiBaseUrl = 'http://localhost:5101/api/'

export const g_queryLogId = ref('tx3pnrnecobyo9tlqaojr4cj9tt90so3')
export const g_fastaFileName = ref('protein.fasta')
export const g_pdbFileName = ref('protein.pdb')
export const g_mechanicalProperties = ref('rigid')
export const g_solubility = ref('hydrophilic')
export const g_positioningDemand = ref('NLS')
export const g_targetProtein = ref('MGKKLRPPGTMTISNLLKQRVRYAPYLKKVKEAHELIPLFKNGQYLGWSGFTGVGTPKAVPEALIDHVEKNNLQGKLRFNLFVGASAGPEENRWAEHDMIIKRAPHQVGKPIAKAINQGRIEFFDKHLSMFPQDLTYGFYTRERKDNKILDYTIIEATAIKEDGSIVPGPSVGGSPEFITVSDKVIIEVNTATPSFEGIHDIDMPVNPPFRKPYPYLKVDDKCGVDSIPVDPEKVVAIVESTMRDQVPPNTPSDDMSRAIAGHLVEFFRNEVKHGRLPENLLPLQSGIGNIANAVIEGLAGAQFKHLTVWTEVLQDSFLDLFENGSLDYATATSVRLTEKGFDRAFANWENFKHRLCLRSQVVSNNPEMIRRLGVIAMNTPVEVDIYAHANSTNVNGSRMLNGLGGSADFLRNAKLSIMHAPSARPTKVDPTGISTIVPMASHVDQTEHDLDILVTDQGLADLRGLSPKERAREIINKCAHPDYQALLTDYLDRAEHYAKKHNCLHEPHMLKNAFKFHTNLAEKGTMKVDSWEPVD')

export const g_matchingResults = ref<PredictionResult[]>([
  {
    fpId: 'FP0001',
    signalId: 'SP0088',
    linkerId: 'LK0015',
    fusionProtein: 'KKRKKDAEAAAKEAAAKMGKKLRPPGTMTISNLLKQRVRYAPYLKKVKEAHELIPLFKNGQYLGWSGFTGVGTPKAVPEALIDHVEKNNLQGKLRFNLFVGASAGPEENRWAEHDMIIKRAPHQVGKPIAKAINQGRIEFFDKHLSMFPQDLTYGFYTRERKDNKILDYTIIEATAIKEDGSIVPGPSVGGSPEFITVSDKVIIEVNTATPSFEGIHDIDMPVNPPFRKPYPYLKVDDKCGVDSIPVDPEKVVAIVESTMRDQVPPNTPSDDMSRAIAGHLVEFFRNEVKHGRLPENLLPLQSGIGNIANAVIEGLAGAQFKHLTVWTEVLQDSFLDLFENGSLDYATATSVRLTEKGFDRAFANWENFKHRLCLRSQVVSNNPEMIRRLGVIAMNTPVEVDIYAHANSTNVNGSRMLNGLGGSADFLRNAKLSIMHAPSARPTKVDPTGISTIVPMASHVDQTEHDLDILVTDQGLADLRGLSPKERAREIINKCAHPDYQALLTDYLDRAEHYAKKHNCLHEPHMLKNAFKFHTNLAEKGTMKVDSWEPVD',
    stabilityScore: 2784.17,
    linker: 'AEAAAKEAAAK',
    signal: 'KKRKKD'
  }
])
